In [1]:
# Array Creation

In [2]:
import numpy as np

In [3]:
ls=[5,9,2,1,7,8]

In [4]:
arr1=np.array(ls)
arr1

array([5, 9, 2, 1, 7, 8])

In [5]:
arr2=np.array([7,2,4,5,1,3])
arr2

array([7, 2, 4, 5, 1, 3])

In [6]:
arr3=np.array(("Ram","Shyam","Sita","Gita"))
arr3

array(['Ram', 'Shyam', 'Sita', 'Gita'], dtype='<U5')

In [7]:
arr4=np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr5=np.arange(5,19,3)
arr5

array([ 5,  8, 11, 14, 17])

In [9]:
arr6=np.linspace(1,10,17)
arr6

array([ 1.    ,  1.5625,  2.125 ,  2.6875,  3.25  ,  3.8125,  4.375 ,
        4.9375,  5.5   ,  6.0625,  6.625 ,  7.1875,  7.75  ,  8.3125,
        8.875 ,  9.4375, 10.    ])

In [10]:
arr7=np.linspace(-4,3,9)
arr7

array([-4.   , -3.125, -2.25 , -1.375, -0.5  ,  0.375,  1.25 ,  2.125,
        3.   ])

In [11]:
# Array Information

In [12]:
arr7.dtype

dtype('float64')

In [13]:
arr3.dtype

dtype('<U5')

In [14]:
arr2.shape

(6,)

In [15]:
arr6.shape

(17,)

In [16]:
arr6.size

17

In [17]:
# Randon function in Python

In [18]:
arr8=np.random.rand()
arr8

0.5398205181059201

In [19]:
arr9=np.random.rand(15)
arr9

array([0.25968739, 0.81502251, 0.91191893, 0.42111041, 0.60404593,
       0.11477823, 0.49669407, 0.62766992, 0.21820134, 0.80717749,
       0.00442221, 0.47044134, 0.67023879, 0.35880842, 0.86525792])

In [20]:
arr10=np.random.randn()
arr10

-1.1104710769906103

In [21]:
arr10=np.random.rand(15)
arr10

array([0.92567271, 0.819576  , 0.50428081, 0.92010488, 0.30796492,
       0.43228738, 0.56451706, 0.50005694, 0.56641152, 0.01121101,
       0.30048082, 0.74038599, 0.57600747, 0.34658247, 0.83179521])

In [22]:
arr11=np.random.randint(30)
arr11

22

In [23]:
arr11=np.random.randint(4,9)
arr11

4

In [24]:
arr11=np.random.randint(12,60,10)
arr11

array([45, 33, 44, 25, 16, 33, 42, 20, 23, 30], dtype=int32)

In [25]:
avg_height=165
std_height=9

height_100_people=np.random.normal(avg_height,std_height,100)
height_100_people

array([161.75923571, 162.18091487, 157.51715693, 172.07844343,
       163.43119242, 169.00133896, 161.46296303, 160.47218014,
       158.58230076, 161.76092935, 161.25129904, 162.85792564,
       173.23314473, 172.03379363, 172.16332497, 163.95410266,
       169.95728295, 164.28584628, 151.4088301 , 159.30422973,
       178.61631748, 165.93850219, 163.80568827, 184.68467718,
       164.50520509, 176.23574314, 156.65468676, 172.3601801 ,
       168.11421442, 162.13688212, 164.30789179, 148.59287089,
       170.91053814, 164.85225679, 169.2443667 , 163.22869712,
       151.5615604 , 155.21688465, 165.50964665, 164.97077242,
       172.09698827, 153.95595539, 170.3120344 , 148.55742608,
       164.37837314, 161.60500285, 156.57159761, 177.56755086,
       164.05859702, 174.41835965, 158.87905483, 161.58889988,
       168.25835461, 171.38028283, 153.96616087, 175.84520425,
       176.78405594, 159.97033093, 168.10448209, 158.56530713,
       174.24523649, 159.01942555, 161.25976422, 169.20

In [26]:
# Finding how many time 5 will occur on top of the dice if dice rolls 10 times

five_on_top=np.random.binomial(10,(1/6),20)
five_on_top

array([1, 2, 0, 2, 1, 1, 0, 2, 2, 3, 1, 0, 2, 1, 5, 1, 1, 2, 2, 2],
      dtype=int32)

In [27]:
#  finding how many time head(1) will occur while tossing a coin in 5 iteration

head_on_top=np.random.binomial(1,(1/2),5)
head_on_top

array([0, 1, 1, 1, 1], dtype=int32)

In [28]:
arr3

array(['Ram', 'Shyam', 'Sita', 'Gita'], dtype='<U5')

In [29]:
random_name=np.random.choice(arr3,3)
random_name

array(['Ram', 'Sita', 'Shyam'], dtype='<U5')

In [30]:
# array resize and reshape

In [31]:
arr14=np.random.randint(4,15,24)
arr14

array([14,  4,  8,  7,  9,  5,  9,  4,  9,  5,  5, 11, 13, 12, 11, 12, 13,
       12, 10, 14,  6, 12, 13, 12], dtype=int32)

In [32]:
arr14.shape

(24,)

In [33]:
arr14.reshape(6,4)

array([[14,  4,  8,  7],
       [ 9,  5,  9,  4],
       [ 9,  5,  5, 11],
       [13, 12, 11, 12],
       [13, 12, 10, 14],
       [ 6, 12, 13, 12]], dtype=int32)

In [34]:
arr14.reshape(3,8)

array([[14,  4,  8,  7,  9,  5,  9,  4],
       [ 9,  5,  5, 11, 13, 12, 11, 12],
       [13, 12, 10, 14,  6, 12, 13, 12]], dtype=int32)

In [35]:
arr14.reshape(4,3,2)

array([[[14,  4],
        [ 8,  7],
        [ 9,  5]],

       [[ 9,  4],
        [ 9,  5],
        [ 5, 11]],

       [[13, 12],
        [11, 12],
        [13, 12]],

       [[10, 14],
        [ 6, 12],
        [13, 12]]], dtype=int32)

In [36]:
arr14.reshape(2,2,3,2)

array([[[[14,  4],
         [ 8,  7],
         [ 9,  5]],

        [[ 9,  4],
         [ 9,  5],
         [ 5, 11]]],


       [[[13, 12],
         [11, 12],
         [13, 12]],

        [[10, 14],
         [ 6, 12],
         [13, 12]]]], dtype=int32)

In [37]:
arr14

array([14,  4,  8,  7,  9,  5,  9,  4,  9,  5,  5, 11, 13, 12, 11, 12, 13,
       12, 10, 14,  6, 12, 13, 12], dtype=int32)

In [38]:
arr14.resize(4,6)

In [39]:
arr14

array([[14,  4,  8,  7,  9,  5],
       [ 9,  4,  9,  5,  5, 11],
       [13, 12, 11, 12, 13, 12],
       [10, 14,  6, 12, 13, 12]], dtype=int32)

In [40]:
arr14.resize(3,8)

In [41]:
arr14

array([[14,  4,  8,  7,  9,  5,  9,  4],
       [ 9,  5,  5, 11, 13, 12, 11, 12],
       [13, 12, 10, 14,  6, 12, 13, 12]], dtype=int32)

In [42]:
arr14.shape

(3, 8)

In [43]:
arr14.size

24

In [44]:
arr14.resize(3,2,2,2)

In [45]:
arr14

array([[[[14,  4],
         [ 8,  7]],

        [[ 9,  5],
         [ 9,  4]]],


       [[[ 9,  5],
         [ 5, 11]],

        [[13, 12],
         [11, 12]]],


       [[[13, 12],
         [10, 14]],

        [[ 6, 12],
         [13, 12]]]], dtype=int32)

In [46]:
arr14.shape

(3, 2, 2, 2)

In [47]:
arr14.size

24

In [48]:
arr14.ravel()

array([14,  4,  8,  7,  9,  5,  9,  4,  9,  5,  5, 11, 13, 12, 11, 12, 13,
       12, 10, 14,  6, 12, 13, 12], dtype=int32)

In [49]:
# NumPy array mathematical operations

In [50]:
a=np.array([[2,6],[-3,1]])
b=np.array([[9,3],[-1,-8]])
a,b

(array([[ 2,  6],
        [-3,  1]]),
 array([[ 9,  3],
        [-1, -8]]))

In [51]:
a+b

array([[11,  9],
       [-4, -7]])

In [52]:
a-b

array([[-7,  3],
       [-2,  9]])

In [53]:
a*b

array([[18, 18],
       [ 3, -8]])

In [54]:
a

array([[ 2,  6],
       [-3,  1]])

In [55]:
a+10

array([[12, 16],
       [ 7, 11]])

In [56]:
a-3

array([[-1,  3],
       [-6, -2]])

In [57]:
a/b

array([[ 0.22222222,  2.        ],
       [ 3.        , -0.125     ]])

In [58]:
b

array([[ 9,  3],
       [-1, -8]])

In [59]:
a+10,b+10

(array([[12, 16],
        [ 7, 11]]),
 array([[19, 13],
        [ 9,  2]]))

In [60]:
# statistical operation

In [61]:
arr15=np.random.randint(1,99,20).reshape(4,5)
arr15


array([[70, 82, 49, 80, 93],
       [30, 91, 51, 87, 14],
       [54, 82, 33, 49, 15],
       [86, 95, 65, 38, 47]], dtype=int32)

In [62]:
arr15.mean()

np.float64(60.55)

In [63]:
arr15.std()

np.float64(25.44498968362927)

In [64]:
arr15.min()

np.int32(14)

In [65]:
arr15.max()

np.int32(95)

In [66]:
np.median(arr15)

np.float64(59.5)

In [67]:
arr15.ravel()

array([70, 82, 49, 80, 93, 30, 91, 51, 87, 14, 54, 82, 33, 49, 15, 86, 95,
       65, 38, 47], dtype=int32)

In [68]:
sorted(arr15.ravel())

[np.int32(14),
 np.int32(15),
 np.int32(30),
 np.int32(33),
 np.int32(38),
 np.int32(47),
 np.int32(49),
 np.int32(49),
 np.int32(51),
 np.int32(54),
 np.int32(65),
 np.int32(70),
 np.int32(80),
 np.int32(82),
 np.int32(82),
 np.int32(86),
 np.int32(87),
 np.int32(91),
 np.int32(93),
 np.int32(95)]

In [69]:
b

array([[ 9,  3],
       [-1, -8]])

In [70]:
np.abs(b)

array([[9, 3],
       [1, 8]])

In [71]:
height_100_people

array([161.75923571, 162.18091487, 157.51715693, 172.07844343,
       163.43119242, 169.00133896, 161.46296303, 160.47218014,
       158.58230076, 161.76092935, 161.25129904, 162.85792564,
       173.23314473, 172.03379363, 172.16332497, 163.95410266,
       169.95728295, 164.28584628, 151.4088301 , 159.30422973,
       178.61631748, 165.93850219, 163.80568827, 184.68467718,
       164.50520509, 176.23574314, 156.65468676, 172.3601801 ,
       168.11421442, 162.13688212, 164.30789179, 148.59287089,
       170.91053814, 164.85225679, 169.2443667 , 163.22869712,
       151.5615604 , 155.21688465, 165.50964665, 164.97077242,
       172.09698827, 153.95595539, 170.3120344 , 148.55742608,
       164.37837314, 161.60500285, 156.57159761, 177.56755086,
       164.05859702, 174.41835965, 158.87905483, 161.58889988,
       168.25835461, 171.38028283, 153.96616087, 175.84520425,
       176.78405594, 159.97033093, 168.10448209, 158.56530713,
       174.24523649, 159.01942555, 161.25976422, 169.20

In [72]:
np.round(height_100_people,decimals=2)

array([161.76, 162.18, 157.52, 172.08, 163.43, 169.  , 161.46, 160.47,
       158.58, 161.76, 161.25, 162.86, 173.23, 172.03, 172.16, 163.95,
       169.96, 164.29, 151.41, 159.3 , 178.62, 165.94, 163.81, 184.68,
       164.51, 176.24, 156.65, 172.36, 168.11, 162.14, 164.31, 148.59,
       170.91, 164.85, 169.24, 163.23, 151.56, 155.22, 165.51, 164.97,
       172.1 , 153.96, 170.31, 148.56, 164.38, 161.61, 156.57, 177.57,
       164.06, 174.42, 158.88, 161.59, 168.26, 171.38, 153.97, 175.85,
       176.78, 159.97, 168.1 , 158.57, 174.25, 159.02, 161.26, 169.21,
       177.66, 181.32, 166.38, 157.38, 148.77, 153.66, 175.65, 169.97,
       157.44, 176.51, 172.2 , 156.65, 162.98, 163.26, 165.79, 170.25,
       164.92, 166.3 , 165.69, 169.43, 176.26, 145.03, 153.72, 182.08,
       163.29, 157.36, 157.47, 150.19, 159.29, 150.77, 175.21, 178.17,
       163.58, 173.73, 156.93, 168.  ])

In [73]:
np.round(height_100_people)

array([162., 162., 158., 172., 163., 169., 161., 160., 159., 162., 161.,
       163., 173., 172., 172., 164., 170., 164., 151., 159., 179., 166.,
       164., 185., 165., 176., 157., 172., 168., 162., 164., 149., 171.,
       165., 169., 163., 152., 155., 166., 165., 172., 154., 170., 149.,
       164., 162., 157., 178., 164., 174., 159., 162., 168., 171., 154.,
       176., 177., 160., 168., 159., 174., 159., 161., 169., 178., 181.,
       166., 157., 149., 154., 176., 170., 157., 177., 172., 157., 163.,
       163., 166., 170., 165., 166., 166., 169., 176., 145., 154., 182.,
       163., 157., 157., 150., 159., 151., 175., 178., 164., 174., 157.,
       168.])

In [74]:
np.mean(arr15)

np.float64(60.55)

In [75]:
np.mean(arr15,axis=1)

array([74.8, 54.6, 46.6, 66.2])

In [76]:
arr15

array([[70, 82, 49, 80, 93],
       [30, 91, 51, 87, 14],
       [54, 82, 33, 49, 15],
       [86, 95, 65, 38, 47]], dtype=int32)

In [77]:
np.mean(arr15,axis=0)

array([60.  , 87.5 , 49.5 , 63.5 , 42.25])

In [78]:
np.sum(arr15)

np.int64(1211)

In [79]:
np.sum(arr15,axis=1)

array([374, 273, 233, 331])

In [80]:
np.sum(arr15,axis=0)

array([240, 350, 198, 254, 169])

In [81]:
arr1

array([5, 9, 2, 1, 7, 8])

In [82]:
np.append(arr1,10)

array([ 5,  9,  2,  1,  7,  8, 10])

In [83]:
np.append(arr15,10)

array([70, 82, 49, 80, 93, 30, 91, 51, 87, 14, 54, 82, 33, 49, 15, 86, 95,
       65, 38, 47, 10])

In [84]:
np.append(arr15,[[10],[10],[10],[10]])

array([70, 82, 49, 80, 93, 30, 91, 51, 87, 14, 54, 82, 33, 49, 15, 86, 95,
       65, 38, 47, 10, 10, 10, 10])

In [85]:
np.append(arr15,[[10],[10],[10],[10]],axis=1)

array([[70, 82, 49, 80, 93, 10],
       [30, 91, 51, 87, 14, 10],
       [54, 82, 33, 49, 15, 10],
       [86, 95, 65, 38, 47, 10]])

In [86]:
np.append(arr15,[[10,10,10,10,10]],axis=0)

array([[70, 82, 49, 80, 93],
       [30, 91, 51, 87, 14],
       [54, 82, 33, 49, 15],
       [86, 95, 65, 38, 47],
       [10, 10, 10, 10, 10]])

In [89]:
data_from_file=np.loadtxt("demo.csv",delimiter=",",dtype=int)
data_from_file

array([[12,  4,  8, 53],
       [85, 21,  9, -1],
       [93, 45, 14,  8]])

In [94]:
data_from_file2=np.genfromtxt("demo2.csv",delimiter=",",dtype=int,filling_values=100)
data_from_file2

array([[ 12,   4,  83,  53],
       [ 85, 100,   9,  -1],
       [ 93,  45,  14,   8]])

In [95]:
arr15

array([[70, 82, 49, 80, 93],
       [30, 91, 51, 87, 14],
       [54, 82, 33, 49, 15],
       [86, 95, 65, 38, 47]], dtype=int32)

In [96]:
np.savetxt("data_from_numpy.csv",arr15,delimiter=",",fmt="%d")

In [98]:
np.save("numpy_data.np",arr15)

In [99]:
np.load("numpy_data.np.npy")

array([[70, 82, 49, 80, 93],
       [30, 91, 51, 87, 14],
       [54, 82, 33, 49, 15],
       [86, 95, 65, 38, 47]], dtype=int32)

In [101]:
p=np.random.randint(1,10,12).reshape(3,4)
p

array([[8, 4, 5, 1],
       [4, 5, 3, 5],
       [7, 4, 9, 1]], dtype=int32)

In [102]:
q=np.random.randint(1,10,20).reshape(4,5)
q

array([[9, 3, 2, 8, 5],
       [6, 3, 3, 7, 6],
       [9, 6, 1, 6, 7],
       [3, 2, 6, 8, 1]], dtype=int32)

In [103]:
p.dot(q)

array([[144,  68,  39, 130, 100],
       [108,  55,  56, 125,  76],
       [171,  89,  41, 146, 123]], dtype=int32)

In [104]:
np.dot(p,q)

array([[144,  68,  39, 130, 100],
       [108,  55,  56, 125,  76],
       [171,  89,  41, 146, 123]], dtype=int32)

In [105]:
zero_arr=np.zeros(4)
zero_arr

array([0., 0., 0., 0.])

In [106]:
zero_arr=np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
ones_arr=np.ones((4,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
i=np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [110]:
p

array([[8, 4, 5, 1],
       [4, 5, 3, 5],
       [7, 4, 9, 1]], dtype=int32)

In [111]:
p.dot(i)

array([[8., 4., 5., 1.],
       [4., 5., 3., 5.],
       [7., 4., 9., 1.]])

In [112]:
sq=np.random.randint(30,60,16).reshape(4,4)
sq

array([[50, 45, 41, 35],
       [54, 56, 49, 46],
       [30, 48, 58, 40],
       [34, 41, 40, 30]], dtype=int32)

In [113]:
sq.trace()

np.int64(194)

In [114]:
sq.T

array([[50, 54, 30, 34],
       [45, 56, 48, 41],
       [41, 49, 58, 40],
       [35, 46, 40, 30]], dtype=int32)

In [115]:
p.T

array([[8, 4, 7],
       [4, 5, 4],
       [5, 3, 9],
       [1, 5, 1]], dtype=int32)

In [116]:
np.linalg.det([[2,1],[4,2]])

np.float64(0.0)

In [121]:
np.linalg.det(sq)

np.float64(-30742.00000000004)

In [119]:
mat=np.array([[2,1],[4,2]])
mat

array([[2, 1],
       [4, 2]])

In [120]:
np.sqrt(mat)

array([[1.41421356, 1.        ],
       [2.        , 1.41421356]])

In [122]:
# create random number matrix of 16 elements and 1, reshape it atleast 3 ways in 2d,3d format and find its trace value and its transpose

In [131]:
z=np.random.randint(1,20,16)
z

array([12,  6,  1, 12, 11,  8, 13, 11, 13,  7, 15,  2,  5, 19, 18,  5],
      dtype=int32)

In [135]:
mat1=np.random.randint(1,50,16)
mat1

array([16,  1, 40, 10, 35, 19, 14,  2, 48, 33, 11, 29, 22, 12, 45, 30],
      dtype=int32)

In [137]:
mat1.reshape(4,4)

array([[16,  1, 40, 10],
       [35, 19, 14,  2],
       [48, 33, 11, 29],
       [22, 12, 45, 30]], dtype=int32)

In [138]:
mat1.reshape(8,2)

array([[16,  1],
       [40, 10],
       [35, 19],
       [14,  2],
       [48, 33],
       [11, 29],
       [22, 12],
       [45, 30]], dtype=int32)

In [139]:
mat1.reshape(2,4,2)

array([[[16,  1],
        [40, 10],
        [35, 19],
        [14,  2]],

       [[48, 33],
        [11, 29],
        [22, 12],
        [45, 30]]], dtype=int32)

In [140]:
mat1.resize(4,4)

In [142]:
mat1.trace()

np.int64(76)

In [143]:
mat1.T

array([[16, 35, 48, 22],
       [ 1, 19, 33, 12],
       [40, 14, 11, 45],
       [10,  2, 29, 30]], dtype=int32)

In [144]:
mat1

array([[16,  1, 40, 10],
       [35, 19, 14,  2],
       [48, 33, 11, 29],
       [22, 12, 45, 30]], dtype=int32)

In [145]:
mat1[0]

array([16,  1, 40, 10], dtype=int32)

In [148]:
mat1[2]

array([48, 33, 11, 29], dtype=int32)

In [149]:
mat1[:,2]

array([40, 14, 11, 45], dtype=int32)

In [150]:
mat1[:,-1]

array([10,  2, 29, 30], dtype=int32)

In [152]:
mat1[1:3,1:3]

array([[19, 14],
       [33, 11]], dtype=int32)

In [153]:
mat1[1:,2:]

array([[14,  2],
       [11, 29],
       [45, 30]], dtype=int32)

In [154]:
mat1

array([[16,  1, 40, 10],
       [35, 19, 14,  2],
       [48, 33, 11, 29],
       [22, 12, 45, 30]], dtype=int32)

In [155]:
mat1[:, 0::2]

array([[16, 40],
       [35, 14],
       [48, 11],
       [22, 45]], dtype=int32)

In [156]:
mat1[0::3, 1:3]

array([[ 1, 40],
       [12, 45]], dtype=int32)

In [161]:
mat1[[0,2,3]]

array([[16,  1, 40, 10],
       [48, 33, 11, 29],
       [22, 12, 45, 30]], dtype=int32)

In [162]:
mat1[[0,2,3],2]

array([40, 11, 45], dtype=int32)

In [163]:
mat1[[0,2,3],2:]

array([[40, 10],
       [11, 29],
       [45, 30]], dtype=int32)

In [164]:
arr20=np.arange(1,101).reshape(10,10).T

In [165]:
arr20

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [166]:
# # [[32,42,52],
# [33,43,53]]

In [167]:
# [[33,  43,  53,  63,  73,  83,  93],
# [34,  44,  54,  64,  74,  84,  94],
# [36,  46,  56,  66,  76,  86,  96],
# [38,  48,  58,  68,  78,  88,  98]]

In [168]:
# [[21,41,61],
#  [23,43,63],
#  [25,45,65]]

In [169]:
# [[23,53,63,83],
#  [25,55,65,85],
#  [27,57,67,87],
#  [29,59,69,89]]

In [175]:
arr20[1:3,3:6]

array([[32, 42, 52],
       [33, 43, 53]])

In [188]:
arr20[2:8,3:]

array([[33, 43, 53, 63, 73, 83, 93],
       [34, 44, 54, 64, 74, 84, 94],
       [35, 45, 55, 65, 75, 85, 95],
       [36, 46, 56, 66, 76, 86, 96],
       [37, 47, 57, 67, 77, 87, 97],
       [38, 48, 58, 68, 78, 88, 98]])